### ISSUE TITLE
SWS_REGIONSFROMITEMS - BUG - creates regions with IDs already used by other regions

### ISSUE THREAD

**Issue by Addiktion** [Jeff0S/sws#706]
This will cause regions loss.

Does not happen all the time, I haven't been able to fully understand how to reproduce.

**Comment by Breeder** [comment]
In cases where bug is not straight forward to reproduce, we can't do anything if we don't have the exact repro steps/example project/sws and reaper version etc...

This action is using the API AddProjectMarker() with wantidx = -1 so that means we aren't changing any IDs nor care about them - REAPER should create region with proper (first unused) ID.

So this as well may be a bug in REAPER API...but to see if we can circumvent we first must be able to reproduce it

**Comment by Addiktion** [comment]
Ok I see, thank you for checking.

I know it is way easier with steps to reproduce, I tried to.
Will let you know when I find the reason.

**Comment by Jeff0S** [comment]
no news == good news, closing.
