### ISSUE TITLE
Feature Request : Contextual Action

### ISSUE THREAD

**Issue by iNX974** [Jeff0S/sws#710]
Like Contextual Toolbar, why not triggering some action depending the mouse focus.

**Comment by Breeder** [comment]
Duplicate of #666

Btw, this is already possible with exported SWS API...even if you don't know how to code this should be quite easy...here is an example that calls both actions and other API to change stuff based on where mouse cursor is.
Note that this is EEL script (faster flavor of ReaScript, and requires REAPER 5 pre)

```
// Call BR_GetMouseCursorContext API from SWS to get current details for stuff under mouse cursor
extension_api("BR_GetMouseCursorContext", #window, #segment, #details);

// If mouse is over TCP track, execute this
!strcmp(#window, "tcp") && !strcmp(#segment, "track") ?
(
  Main_OnCommand(40113, 0); // Call the action "View: Toggle track zoom to maximum height"...we got that number by right-clicking the action in action list and selecting "Copy selected action command ID"
)

// If mouse is over arrange item, execute this
: !strcmp(#window, "arrange") && !strcmp(#segment, "track") && !strcmp(#details, "item") ?
(
  Main_OnCommand(NamedCommandLookup("_SWS_ITEMZOOM"), 0); // Call the action "SWS: Zoom to selected item"...we got that string by right-clicking the action n action list and selecting "Copy selected action command ID"
)

// If mouse is either over TCP envelope panel or arrange envelope lane execute this
: (!strcmp(#window, "tcp") && !strcmp(#segment, "envelope")) || (!strcmp(#window, "arrange") && !strcmp(#segment, "envelope")) ?
(
  SetCursorContext(2, extension_api("BR_GetMouseCursorContext_Envelope", 0)); // instead of calling the actions, you can also use the API which can offer a lot of additional stuff
  UpdateArrange() // need to call this to update display after selecting envelope
)
```
If you're really having problems with understanding this, I'm sure that if you ask on the forums under ReaScript section, someone will create needed script for you.


Btw, this is exactly the reason I think this feature is best used from ReaScript and not some SWS GUI. Why? Because let's face it...there aren't many things you could do solely by using actions depending on where the mouse is. Contextual toolbars employ a lot of different hacks *(make toolbar topmost, change it's position, auto close etc...)* which aren't really simple to do from a script, so doing them from SWS was justified. 

Using ReaScript on the other hand allows for much more finer stuff *(because SWS API can also tell you which item/track/envelope is at mouse cursor, time at mouse cursor etc...)*
Recreating this just for a few actions feels a bit like an overkill and since it's already quite possible with ReaScript,  I'm not sure I want to dedicate my free time doing it.

Of course, that doesn't means someone else won't do it for SWS...but until that happens, you can always try with the script :)

**Comment by iNX974** [comment]
Thank you, it's easiely comprehensive.
