### ISSUE TITLE
Markers don't get noticed by reaper/action markers not activated when at repeating time selection start or end

### ISSUE THREAD

**Issue by Duskmoon** [Jeff0S/sws#723]
Hello,

I have noticed some things about the action markers concerning several actions when i tried to use them to enhance my workflow

If for instance a marker is carrying an action like 'start/stop recording after 1 measure' or 'toggle record' or similar actions and the marker is placed at the end of a repeating loop it doesn't initialize the action (wich for lots of functions seems contradictive to reaper recording a new take when in a repeating time selection)
nor if a marker is set at the very beginning of a loop and the loop is at its 2nd cycle
even then it doesn't trigger (however,when playback is started from this position,it does trigger?)

If that same marker is placed in the middle of the loop and is passed it does triggers the action
 
I can imagine that this is not the behavior that's intended and thought it important to notify you of this

**Comment by Jeff0S** [comment]
Yes, this is a know limitation of marker actions: the timing is "good enough" most of the time, but not sample accurate (up to 30 ms of latency in the very worst case) because actions in general can't be triggered in a sample accurate way -- unless anticipated/implemented as such, of course (like Start/stop recording at next measure for ex.)
