### ISSUE TITLE
Descriptions in Label Processor are not aligned

### ISSUE THREAD

**Issue by X-Raym** [Jeff0S/sws#725]
Descriptions in Label Processor are not aligned.

(windows 7, SWS 2.7.1 #0).

Screenshot here
![label processor 2015-06-01 21 16 35](https://cloud.githubusercontent.com/assets/7224315/7921184/f539625e-08a3-11e5-8108-7e448c8999b6.png)

**Comment by Breeder** [comment]
b5451edbb9543aa14740bb10b1e85c65e02b9ef0 is not a proper fix (because fonts can be different across operating systems), but I added a few more tab characters so there's at least some space - looks normal on Win 8.1 now

For the reference, this could be fixed using a method I'm using for loudness wildcards:
https://github.com/Jeff0S/sws/blob/b5451edbb9543aa14740bb10b1e85c65e02b9ef0/Breeder/BR_Loudness.cpp#L73-L102
https://github.com/Jeff0S/sws/blob/b5451edbb9543aa14740bb10b1e85c65e02b9ef0/Breeder/BR_Loudness.cpp#L2677-L2722

**Comment by Breeder** [comment]
Heh...let's keep it open since it's not properly fixed :)

**Comment by X-Raym** [comment]
Thanks for your consideration on this. Should be way more easy to read :)
